### ISSUE TITLE
0pdd doesn't work properly

### ISSUE THREAD

**Issue by krzyk** [yegor256/qulice#889]
0pdd doesn't close issues with removed puzzles.
The reason is probably because `pdd` is run by 0pdd using the settings in .pdd and not by looking at the S3 content that we send to it using s3cmd during merge.

Or maybe there should be a webhook defined to pdd/0pdd.

**Comment by krzyk** [comment]
@yegor256 Could you look into this? Maybe webhook to 0ppd is not defined in qulice repo?

**Comment by yegor256** [comment]
@krzyk it seems to work: http://www.0pdd.com/log?name=teamed/qulice I didn't change anything for a long time

**Comment by krzyk** [comment]
@yegor256 Hmm, but there are no new issues created from todo tags (https://github.com/teamed/qulice/pull/892) and issues are not closed for removed puzzles (#850). Although the log looks (I think correct):
- http://www.0pdd.com/log-item?repo=teamed/qulice&tag=save-1525035555 (todo removed)
- http://www.0pdd.com/log-item?repo=teamed/qulice&tag=save-1525189135 (todo added)

**Comment by yegor256** [comment]
@krzyk see the problem we just fixed: https://github.com/yegor256/0pdd/issues/205 Try to push something to the repo. 0pdd should work properly now.

**Comment by krzyk** [comment]
@yegor256 still the same problem, there were few pushes to the repo, but the todo issues haven't been added or removed

**Comment by yegor256** [comment]
@krzyk fixed already
